---
micronaut:
    server:
        port: 8081
    application:
        name: kafkatomongo-to-mongo
---
kafka:
    bootstrap:
        servers: kafka:9092
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"