---
micronaut:
    server:
        port: 8081
    application:
        name: kafka-to-mongo
---
kafka:
    bootstrap:
        servers: kafka:9092
---
mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
consul:
    client:
        registration:
            enabled: true
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"